CREATE TABLE `User` (
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(20) NOT NULL,
	`fullName` VARCHAR(20) NOT NULL,
	`password` VARCHAR(20) NOT NULL,
	`email` VARCHAR(50) NOT NULL,
	`age` INT NOT NULL,
	`createDate` DATE NOT NULL,
	PRIMARY KEY (`id`)
)